### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by ngraymon** [ngraymon/DNN-SE#26]
per this error which comes up when using numpy  1.21
```python
Traceback (most recent call last):
  File "driver.py", line 753, in <module>
    main(molecule, spins)
  File "driver.py", line 696, in main
    mcmc_object = prepare_mcmc(mcmc_config, network_object, init_means, precision)
  File "driver.py", line 635, in prepare_mcmc
    mcmc_object = MonteCarlo(
  File "/DNN-SE/monte_carlo.py", line 103, in __init__
    self.walkers = self._initial_random_states()
  File "/DNN-SE/monte_carlo.py", line 161, in _initial_random_states
    samples = rng.normal(
  File "_generator.pyx", line 1131, in numpy.random._generator.Generator.normal
  File "_common.pyx", line 562, in numpy.random._common.cont
  File "_common.pyx", line 480, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 229, in numpy.random._common.validate_output_shape
ValueError: Output size (3, 10, 1) is not compatible with broadcast dimensions of inputs (3, 10, 3).
```

see [here](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp), we should add a requirements file to the repository to fix the versions of the packages we use.

**Comment by ngraymon** [comment]
Okay seems that `tensorflow==0.11` and `torch=1.10` and `numpy=1.19` seem to work

**Comment by ngraymon** [comment]
[helpful](https://pytorch.org/get-started/locally/)
